export type ProfileIdentifier = string;

// Zora profile identifiers (handles or wallet addresses) to source the home feed from.
// Replace these with the profiles you want.
export const FEED_PROFILES: ProfileIdentifier[] = [
  "cyshimi",
  "seedcomputer",
  "rebudigital",
  "brendyzinha",
  "elbi",
  "tir3d",
  "lucasborges",
  "pwdro",
  "l444u",
  "qabqabqab",
  "4nd7ro",
  "femzor",
  "ileogivel",
  "almaseleno",
  "edugualberto",
  "gumajoana",
  "mlkbrutal",
  "numadessas",
  "intraalma",
  "internetjunk",
  "lvqkiinhas",
  "marianalima",
  "ygoralvesl",
  "donojulian",
  "thetitleisangul",
  "ultrababi",
  "rawrrawrchloe",
  "cutieboneca",
  "gabepierrot",
  "danificada",
  "franciscoskt",
  "skatehacker",
  "willdias",
  "zimardrp",
  "humbertoperes",
  "nogenta",
];
